#!/usr/bin/env python3
"""Generate a complete requirements file for a full ptools install.

``ptools`` declares its mandatory dependencies in ``pyproject.toml``, but
several subcommands also depend on *optional* libraries that are only
guarded by :mod:`ptools.utils.require` decorators at the call site —
think ``openai``, ``prompt_toolkit``, ``pygments`` and friends.

This script imports every module under :mod:`ptools`, which causes those
decorators to fire and register themselves into the requirement
announcement registry (see :func:`ptools.utils.require.announced_requirements`).
It then combines what it learns there with the base dependencies from
``pyproject.toml`` and prints a ``requirements.txt``-style document to
stdout that pip can consume directly:

.. code-block:: bash

    python scripts/generate_requirements.py > full-requirements.txt
    pip install -r full-requirements.txt

Binaries and API keys that ``require`` decorators announce are listed as
comments at the top of the output since pip cannot install them.
"""

from __future__ import annotations

import argparse
import importlib
import pkgutil
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
PYPROJECT = REPO_ROOT / "pyproject.toml"


def _load_toml(path: Path) -> dict:
    try:
        import tomllib  # type: ignore[import-not-found]
    except ModuleNotFoundError:  # pragma: no cover — Python 3.10
        import tomli as tomllib  # type: ignore[import-not-found]
    return tomllib.loads(path.read_text())


def _load_base_dependencies() -> list[str]:
    data = _load_toml(PYPROJECT)
    return list(data.get("project", {}).get("dependencies", []))


_REQUIREMENT_NAME_RE = re.compile(r"^([A-Za-z0-9_.\-]+)")


def _pip_name_of(requirement_string: str) -> str:
    """Extract the distribution name from a PEP 508 requirement string."""
    match = _REQUIREMENT_NAME_RE.match(requirement_string.strip())
    return (match.group(1) if match else requirement_string).lower().replace("_", "-")


def _import_all_ptools_modules() -> list[tuple[str, str]]:
    """Walk the :mod:`ptools` package and import every submodule.

    Returns a list of ``(module_name, error_message)`` pairs for any
    module that failed to import — these are surfaced as comments in
    the generated requirements file so the user can investigate.
    """
    import ptools  # noqa: WPS433 — deferred on purpose

    failures: list[tuple[str, str]] = []
    for module_info in pkgutil.walk_packages(ptools.__path__, prefix="ptools."):
        try:
            importlib.import_module(module_info.name)
        except Exception as exc:  # noqa: BLE001
            failures.append((module_info.name, f"{type(exc).__name__}: {exc}"))
    return failures


def _format_output(
    base_deps: list[str],
    announced,
    import_failures: list[tuple[str, str]],
) -> str:
    from ptools.utils.require import (
        BinaryRequirement,
        KeyRequirement,
        LibraryRequirement,
    )

    library_reqs = [r for r in announced if isinstance(r, LibraryRequirement)]
    binary_reqs = [r for r in announced if isinstance(r, BinaryRequirement)]
    key_reqs = [r for r in announced if isinstance(r, KeyRequirement)]

    base_names = {_pip_name_of(dep) for dep in base_deps}
    extra_libraries = {}
    for req in library_reqs:
        normalized = _pip_name_of(req.pip_name)
        if normalized in base_names:
            continue
        # Dedup across multiple announcements; prefer the first seen.
        extra_libraries.setdefault(normalized, req.pip_name)

    lines: list[str] = []
    lines.append(
        "# Complete ptools requirements — generated by "
        "scripts/generate_requirements.py."
    )
    lines.append("# Do not edit by hand; regenerate with:")
    lines.append("#   python scripts/generate_requirements.py > full-requirements.txt")
    lines.append("#")
    lines.append(
        "# This file is intentionally NOT referenced from pyproject.toml — "
        "it exists"
    )
    lines.append("# only to make a full install reproducible in one shot.")
    lines.append("")

    if binary_reqs:
        lines.append("# System binaries (install via your OS package manager):")
        for req in binary_reqs:
            joined = f" {req.logical_operator.upper()} ".join(req.names)
            lines.append(f"#   - {joined}")
        lines.append("")

    if key_reqs:
        lines.append("# Environment variables / API keys expected at runtime:")
        for req in key_reqs:
            aliases = ", ".join(req.aliases) if req.aliases else req.name
            lines.append(f"#   - {req.name}  (resolved via: {aliases})")
        lines.append("")

    if import_failures:
        lines.append(
            "# Modules that failed to import during discovery — their "
            "requirements may be under-reported:"
        )
        for name, error in import_failures:
            lines.append(f"#   - {name}: {error}")
        lines.append("")

    lines.append("# --- Base dependencies (from pyproject.toml) ---")
    lines.extend(sorted(base_deps, key=str.lower))

    if extra_libraries:
        lines.append("")
        lines.append(
            "# --- Optional libraries announced by ptools.utils.require ---"
        )
        lines.extend(sorted(extra_libraries.values(), key=str.lower))

    lines.append("")  # trailing newline
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write the generated file to this path instead of stdout.",
    )
    args = parser.parse_args(argv)

    # Make the in-tree source importable without requiring an editable
    # install — mirrors what docs/conf.py does.
    sys.path.insert(0, str(SRC_DIR))

    base_deps = _load_base_dependencies()
    import_failures = _import_all_ptools_modules()

    from ptools.utils.require import announced_requirements

    output = _format_output(base_deps, announced_requirements(), import_failures)

    if args.output:
        args.output.write_text(output)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(output)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
